### ISSUE TITLE
A small number of bugs involve multiple fix commits in one or more repositories

### ISSUE THREAD

**Issue by ChrisTimperley** [robust-rosin/robust#379] opened 2020-10-21 14:00 UTC
For example, `0027b57` contains two fix commits in the same repository, and `fd6b589` contains two commits across two repositories. The bug description format should be adjusted to better support such cases. A simple fix is to transform the `repo` and `hash` fields in `fix` into lists. However, this introduces some ambiguity into which commits belong to which repo.

A better alternative is to replace both of these fields with a `commits` field, which describes each of the fix commits. Fix commits would be described by an object specifying `repo` and `hash`, and could also specify some useful information for the purpose of analysis (e.g., `stats`, `files`, `committer`, `date`, etc).

**Comment by gavanderhoorn** [comment] 2020-10-21 14:23
Isn't this a duplicate of #162?

**Comment by wasowski** [comment] 2020-10-21 16:01
go ahead @ChrisTimperley !

**Closed** 2020-11-18 01:04 UTC
Labels: bug-descriptions, refactoring
